
name: CI

on:
  pull_request:

jobs:
  basics:
    strategy:
      matrix:
        node: ['14', '16', '17']
    runs-on: ubuntu-latest
    name: node ${{ matrix.node }}

    steps:
    - uses: actions/checkout@v2
    - run: npm install -g coveralls nyc

    - run: npm ci
    - run: npm run test:lint
    - run: npm run test:coverage

    - run: nyc report --reporter=text-lcov | coveralls || echo 'Failed to upload to coveralls...'
    # - run: npm run semantic-release
